# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zee < Formula
  desc "Push-to-talk transcription for macOS"
  homepage "https://github.com/sumerc/zee"
  version "0.3.6"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sumerc/zee/releases/download/v0.3.6/zee_darwin_amd64.tar.gz"
    sha256 "b954c4359b1e7cb66e4922c2475cbe16ba1f4ede00848596dfabf642c98a5bbf"

    define_method(:install) do
      bin.install "zee"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sumerc/zee/releases/download/v0.3.6/zee_darwin_arm64.tar.gz"
    sha256 "34cfbef2ac48f7ee1049c0a2952fba5aeb894633b3caef52be8b025f8bd2f98b"

    define_method(:install) do
      bin.install "zee"
    end
  end

  test do
    system "#{bin}/zee", "-version"
  end
end
