# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zee < Formula
  desc "Push-to-talk transcription for macOS"
  homepage "https://github.com/sumerc/zee"
  version "0.3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sumerc/zee/releases/download/v0.3.0/zee_darwin_amd64.tar.gz"
    sha256 "624457aabcb840a11c38e2ece2eebd9ed26be8ee657876078346db42517b298a"

    define_method(:install) do
      bin.install "zee"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sumerc/zee/releases/download/v0.3.0/zee_darwin_arm64.tar.gz"
    sha256 "bb5886f343d6e08a72fa09fd7b618e9fa0a533da1d7f77897b8e6751ee401ac9"

    define_method(:install) do
      bin.install "zee"
    end
  end

  test do
    system "#{bin}/zee", "-version"
  end
end
