# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zee < Formula
  desc "Push-to-talk transcription for macOS"
  homepage "https://github.com/sumerc/zee"
  version "0.3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sumerc/zee/releases/download/v0.3.0/zee_darwin_amd64.tar.gz"
    sha256 "ac7aa0e1bd86ff933917183fe38627ff20b3ea9002c60846367427bcaea7cd13"

    define_method(:install) do
      bin.install "zee"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sumerc/zee/releases/download/v0.3.0/zee_darwin_arm64.tar.gz"
    sha256 "e92bc3ef756bf566c22a807631fb62e15a039f407d96b1d39dda8eea03300dc6"

    define_method(:install) do
      bin.install "zee"
    end
  end

  test do
    system "#{bin}/zee", "-version"
  end
end
